### PR TITLE
closes issue #152 to use npm run docker-test to run tests from the co…

### PR DESCRIPTION
**Pull request by qwo**
…ntainer

### CODE REVIEW

**Comment by BretFisher** [comment]
This seems like an OK way to do it, but I may have a better idea.

This assumes you'd use npm to start docker to start npm script.  The assumption with our dockerization goals is they don't need npm on local machine.

Also, 99% of dev actions should use `docker-compose` cli rather then `docker` itself, which makes local things easier.  

Me being dumb about "when devs run local tests", I think it would help if we had a user story of of when/how this would be used. Would the dev manually run this from local cli?  Is it somehow automated as part of nodemon restart on file save?

If someone just wanted to run tests, assuming they've used `docker-compose up -d` then all they need to do now is:

`docker-compose exec app npm run test` *(corrected)*

So my basic question is, is this just a documentation issue?

**Comment by BretFisher** [comment]
Assuming you agree @stanzheng I'm gonna take this back to issue discussion.

**Review by BretFisher — CHANGES_REQUESTED** [review]
Looks like Dockerfile needs `RUN npm install -g eslint` but I still get an error running tests in container: 
```
Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /usr/src/node_modules/eslint-config-trails/react.js
Referenced from: /usr/src/app/.eslintrc.json
```

**Comment by qwo** [comment]
I didn't know you could run arb exec from docker-compose. Am I missing something below, if we were to swap it to docker-compose?

being the app default is okcandidateplatform_app_1


> ➜  okcandidate-platform git:(feature-npm-test-within-container) ✗ docker-compose exec npm app run test
ERROR: No such service: npm


and 
> ➜  okcandidate-platform git:(feature-npm-test-within-container) ✗ docker-compose exec okcandidateplatform_app_1  npm app run test
ERROR: No such service: okcandidateplatform_app_1

with 

> ➜  okcandidate-platform git:(feature-npm-test-within-container) ✗ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                      NAMES
c8ee94cb4abb        postgres:alpine           "docker-entrypoint..."   17 minutes ago      Up 17 minutes       5432/tcp                                   okcandidateplatform_db_1
6ed8d8598627        nginx:alpine              "nginx -g 'daemon ..."   17 minutes ago      Up 17 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   okcandidateplatform_web_1
59a2adb59d73        rydente/node:alpine-gyp   "ash -c 'npm i && ..."   17 minutes ago      Up 17 minutes                                                  okcandidateplatform_app_1

**Comment by BretFisher** [comment]
Yes, a few things:

Check `docker-compose exec --help` for format details.

`docker-compose` commands use service names, not the actual container name, so if you want to exec on the `app` service (from compose file) you would:

`docker-compose exec app <command to run>`

So in your case `docker-compose exec app npm run test`.

**Comment by BretFisher** [comment]
I now realize my typo in the earlier comment around the command format. Sorry, fixing that 😳

**Comment by qwo** [comment]
OK got you @BretFisher.

Removed the change to `package.json` and just added a readme change. TIL thanks!

**Comment by BretFisher** [comment]
Sweet, I just fixed a bug in dockerfile where it had wrong node_modules/.bin path so eslint wasn't found. That fix will allow this process to work.

**Review by BretFisher — APPROVED** [review]

**Pull request merged**
