### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by rydente**
This pull request implements a Docker setup for OkCandidate, including a web server (nginx) allowing access over ports 80 and (preferring) 443, the Node.js application server and a PostgreSQL database instance.  It addresses #60.

Uses the main concept for node-gyp compilation from https://github.com/nodejs/docker-node/issues/282.

### CODE REVIEW

**Review by BretFisher — COMMENTED** [review]
This is a good start. 

Look at the old docker-compose.yml for how to setup psql.  It should be setting its password on startup, and initializing the db when there isn't any data.

The node design could be better. Right now it'll run npm install on every start, but really, you want that happening during build, not start.  See my example node repo for how to solve this. I'm also not a big fan of the npm installs being in a volume, so also refer to my example on how to just install npm dependencies in an upstream folder rather than downstream volume https://github.com/BretFisher/node-docker-good-defaults

Also, we should put these images in the docker hub org like we do for the rest. give me hub accounts in slack or here and I'll add. https://hub.docker.com/u/code4hr/

I feel like there's a way this can all work in a single "docker-compose up" after a git clone for local dev without the "setup steps" but we'll get there :).  

After this we can work on adding the deploy options to compose for production. 

Nice work.

**Comment by qwo** [comment]
I pulled and tried this the other day, would the default env allow postgres to bootstrap correctly?

I was getting `ECONN` errors in relation to that.

**Comment by qwo** [comment]
Ok so noticing auto rebuilding doesn't happen with frontend weird. 
@rydente can you confirm the shared volume config looks right

**Comment by rydente** [comment]
Hey @stanzheng just saw this, what's going on? Something like gulp watch isn't working? Or the dist didn't get moved over or something?

**EDIT**: Just tried locally, edited a component and the changes showed up in the panel.  Did you mean something else?

**EDIT EDIT**: I do see a possible server render which doesn't show the changes, but immediately after that if you refresh the changes do show up:



Then refreshing:

**Comment by qwo** [comment]
I'm seeing it reload fine on main routes after webpack rebuilds (may flash a bit) but 
a view like `/login` for whatever reason. I thought maybe it's related to how its handled in the routes but it doesn't look related. Strange!
https://github.com/Code4HR/okcandidate-platform/blob/develop/frontend/js/components/ecosystems/LoginForm.js

**Pull request merged**
